# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seatlink.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_fifthwindow(object):

    def signup(self):
        name=self.lineEdit.text()
        user=self.lineEdit_2.text()
       
        
        conn = sqlite3.connect('testdb3.db')
        c = conn.cursor()
        c.execute('CREATE TABLE IF NOT EXISTS student(name VARCHAR ,username VARCHAR)')
        c.execute("INSERT INTO student (name ,username) VALUES (?,?)",(name ,user))
        conn.commit()
        signup()
        

    def setupUi(self, fifthwindow):
        fifthwindow.setObjectName("fifthwindow")
        fifthwindow.resize(1366, 768)
        fifthwindow.setStyleSheet("background-color:white")
        self.centralwidget = QtWidgets.QWidget(fifthwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(970, 640, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.signup)
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 90, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;")
        self.label_7.setObjectName("label_7")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(680, 190, 21, 31))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(673, 205, 31, 41))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(550, 485, 141, 31))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(710, 435, 113, 20))
        self.lineEdit_3.setStyleSheet("border:none;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        
        
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(690, 485, 131, 31))
        self.line_21.setLineWidth(1)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(550, 195, 141, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(700, 195, 161, 21))
        self.line_23.setLineWidth(1)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(859, 205, 41, 41))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(540, 205, 20, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_25.setFont(font)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(860, 490, 31, 21))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(870, 205, 16, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_27.setFont(font)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(580, 435, 71, 16))
        self.label_8.setObjectName("label_8")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(863, 485, 31, 16))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(680, 205, 16, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_29.setFont(font)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(820, 480, 41, 41))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 275, 113, 20))
        self.lineEdit_2.setStyleSheet("border:none;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(580, 285, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(716, 235, 111, 16))
        self.label_10.setObjectName("label_10")
    
        
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 235, 71, 16))
        self.label_11.setObjectName("label_11")
        self.line_31 = QtWidgets.QFrame(self.centralwidget)
        self.line_31.setGeometry(QtCore.QRect(680, 205, 16, 16))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(580, 335, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(580, 375, 101, 21))
        self.label_13.setObjectName("label_13")
        self.line_32 = QtWidgets.QFrame(self.centralwidget)
        self.line_32.setGeometry(QtCore.QRect(860, 485, 16, 31))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(710, 325, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.line_33 = QtWidgets.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(863, 475, 31, 21))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.centralwidget)
        self.line_34.setGeometry(QtCore.QRect(860, 190, 16, 31))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(710, 375, 141, 20))
        self.lineEdit.setStyleSheet("border:none;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(863, 210, 31, 31))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")

        
        
        
        fifthwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(fifthwindow)
        self.statusbar.setObjectName("statusbar")
        fifthwindow.setStatusBar(self.statusbar)

        self.retranslateUi(fifthwindow)
        QtCore.QMetaObject.connectSlotsByName(fifthwindow)
        

    def retranslateUi(self, fifthwindow):
        _translate = QtCore.QCoreApplication.translate
        fifthwindow.setWindowTitle(_translate("fifthwindow", "MainWindow"))
        self.pushButton.setText(_translate("fifthwindow", "Print"))
        self.label_7.setText(_translate("fifthwindow", "Ticket Details"))
        self.label_8.setText(_translate("fifthwindow", "Show timings"))
        self.label_9.setText(_translate("fifthwindow", "Movie name"))
        self.label_10.setText(_translate("fifthwindow", "23424243212"))
        self.label_11.setText(_translate("fifthwindow", "Transaction ID"))
        self.label_12.setText(_translate("fifthwindow", "Date"))
        self.label_13.setText(_translate("fifthwindow", "Selected seats are"))
        self.lineEdit_2.setText(_translate("fifthwindow", "12:00 PM"))
        self.lineEdit_3.setText(_translate("fifthwindow", "Blade runner : 2049"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fifthwindow = QtWidgets.QMainWindow()
    ui = Ui_fifthwindow()
    ui.setupUi(fifthwindow)
    fifthwindow.show()
    sys.exit(app.exec_())
